-- Shorten function name
local keymap = vim.api.nvim_set_keymap
local opts = { noremap = true, silent = true }
local term_opts = { silent = true }

-- Modes
--   normal_mode = "n",
--   insert_mode = "i",
--   visual_mode = "v",
--   visual_block_mode = "x",
--   term_mode = "t",
--   command_mode = "c",

--Remap leader key
keymap("", "<Space>", "<Nop>", opts)
vim.g.mapleader = " "
vim.g.maplocalleader = " "

-- -- Normal --
--
-- -- Useful command modes with leader
-- keymap("n", "<leader>wa", ":wa<CR>", opts)
-- keymap("n", "<leader>q", ":q<CR>", opts)
-- keymap("n", "<leader>q", ":q<CR>", opts)
-- keymap("n", "<leader>Q", ":q!<CR>", opts)
--
-- -- Better cursor movement
-- keymap("n", "H", "^", opts)
-- keymap("n", "L", "$", opts)
--
-- -- Better window split
-- keymap("n", "<leader>ws", ":split<CR>", opts)
-- keymap("n", "<leader>wv", ":vsplit<CR>", opts)
--
-- -- ToggleTerm
-- keymap("n", "<leader>t", ":ToggleTerm<CR>", term_opts)
--
-- -- Better window navigation
-- keymap("n", "<leader>wh", "<C-w>h", opts)
-- keymap("n", "<leader>wj", "<C-w>j", opts)
-- keymap("n", "<leader>wk", "<C-w>k", opts)
-- keymap("n", "<leader>wl", "<C-w>l", opts)
--
-- --keymap("n", "<leader>e", ":Lex 30<cr>", opts)
-- keymap("n", "<leader>.E", ":NvimTreeToggle<CR>", opts)
-- keymap("n", "<leader>.e", ":NvimTreeFocus<CR>", opts)
--
-- keymap("n", "<leader>ff", ":Telescope find_files<CR>", opts)
-- keymap("n", "<leader>ft", ":Telescope live_grep<CR>", opts)
--
-- -- Resize with arrows
-- keymap("n", "<C-Up>", ":resize +2<CR>", opts)
-- keymap("n", "<C-Down>", ":resize -2<CR>", opts)
-- keymap("n", "<C-Left>", ":vertical resize -2<CR>", opts)
-- keymap("n", "<C-Right>", ":vertical resize +2<CR>", opts)
--
-- -- Navigate buffers
-- keymap("n", "<leader>w;", ":BufferLineCycleNext<CR>", opts)
-- keymap("n", "<leader>w,", ":BufferLineCyclePrev<CR>", opts)
-- keymap("n", "<leader>wp", ":BufferLineTogglePin<CR>", opts)
-- keymap("n", "<leader>wcl", ":BufferLineCloseRight<CR>", opts)
-- keymap("n", "<leader>wch", ":BufferLineCloseLeft<CR>", opts)
-- keymap("n", "<leader>ww", ":BufferLinePick<CR>", opts)
-- keymap("n", "<leader>w=", ":BufferLineSortByTabs<CR>", opts)
-- keymap("n", "<leader>w1", ":BufferLineGoToBuffer 1<CR>", opts)
-- keymap("n", "<leader>w2", ":BufferLineGoToBuffer 2<CR>", opts)
-- keymap("n", "<leader>w3", ":BufferLineGoToBuffer 3<CR>", opts)
-- keymap("n", "<leader>w4", ":BufferLineGoToBuffer 4<CR>", opts)
-- keymap("n", "<leader>w5", ":BufferLineGoToBuffer 5<CR>", opts)
-- keymap("n", "<leader>w6", ":BufferLineGoToBuffer 6<CR>", opts)
-- keymap("n", "<leader>w7", ":BufferLineGoToBuffer 7<CR>", opts)
-- keymap("n", "<leader>w8", ":BufferLineGoToBuffer 9<CR>", opts)
-- keymap("n", "<leader>w9", ":BufferLineGoToBuffer 9<CR>", opts)
--
-- -- Insert --
-- -- Press jk fast to enter
-- keymap("i", "jk", "<ESC>", opts)
--
-- -- Visual --
--
-- -- Better cursor movement
-- keymap("v", "H", "^", opts)
-- keymap("v", "L", "$", opts)
--
-- -- Stay in indent mode
-- -- keymap("v", "<", "<gv", opts)
-- -- keymap("v", ">", ">gv", opts)
--
-- -- Move text up and down
-- -- keymap("v", "<A-j>", ":m .+1<CR>==", opts)
-- -- keymap("v", "<A-k>", ":m .-2<CR>==", opts)
-- -- keymap("v", "p", '"_dP', opts)
--
-- -- Visual Block --
--
-- -- Better cursor movement
-- keymap("v", "H", "^", opts)
-- keymap("v", "L", "$", opts)
--
-- -- Move text up and down
-- keymap("x", "J", ":move '>+1<CR>gv-gv", opts)
-- keymap("x", "K", ":move '<-2<CR>gv-gv", opts)
-- keymap("x", "<A-j>", ":move '>+1<CR>gv-gv", opts)
-- keymap("x", "<A-k>", ":move '<-2<CR>gv-gv", opts)
--
-- -- Terminal --
-- -- Better terminal navigation
-- keymap("t", "<C-h>", "<C-\\><C-N><C-w>h", term_opts)
-- keymap("t", "<C-j>", "<C-\\><C-N><C-w>j", term_opts)
-- keymap("t", "<C-k>", "<C-\\><C-N><C-w>k", term_opts)
-- keymap("t", "<C-l>", "<C-\\><C-N><C-w>l", term_opts)
-- keymap("t", "<Esc>", "<C-\\><C-n>", term_opts)
-- keymap("t", "<leader>t", "<C-\\><C-n>:ToggleTerm<CR>", term_opts)
--
-- -- Trouble.nvim
-- keymap("n", "gee", ":TroubleToggle<CR>", opts)
--
-- -- Packer
-- keymap("n", "<leader><leader>ps", ":PackerSync<CR>", opts)
--
-- -- vim.keymap.set("n", "<leader>.e", vim.cmd.Ex)
--
-- -- vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
--
-- -- vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
-- -- vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
--
-- -- vim.keymap.set("n", "J", "mzJ`z")
-- -- vim.keymap.set("n", "<C-d>", "<C-d>zz")
-- -- vim.keymap.set("n", "<C-u>", "<C-u>zz")
-- -- vim.keymap.set("n", "n", "nzzzv")
-- -- vim.keymap.set("n", "N", "Nzzzv")
--
-- -- vim.keymap.set("n", "<leader>vwm", function()
-- --     require("vim-with-me").StartVimWithMe()
-- -- end)
-- -- vim.keymap.set("n", "<leader>svwm", function()
-- --     require("vim-with-me").StopVimWithMe()
-- -- end)
--
-- -- -- greatest remap ever
-- -- vim.keymap.set("x", "<leader>p", [["_dP]])
--
-- -- -- next greatest remap ever : asbjornHaland
-- -- vim.keymap.set({"n", "v"}, "<leader>y", [["+y]])
-- -- vim.keymap.set("n", "<leader>Y", [["+Y]])
--
-- -- vim.keymap.set({"n", "v"}, "<leader>d", [["_d]])
--
-- -- -- This is going to get me cancelled
-- -- vim.keymap.set("i", "<C-c>", "<Esc>")
--
-- -- vim.keymap.set("n", "Q", "<nop>")
-- -- vim.keymap.set("n", "<C-f>", "<cmd>silent !tmux neww tmux-sessionizer<CR>")
-- -- vim.keymap.set("n", "<leader>f", vim.lsp.buf.format)
--
-- -- vim.keymap.set("n", "<C-k>", "<cmd>cnext<CR>zz")
-- -- vim.keymap.set("n", "<C-j>", "<cmd>cprev<CR>zz")
-- -- vim.keymap.set("n", "<leader>k", "<cmd>lnext<CR>zz")
-- -- vim.keymap.set("n", "<leader>j", "<cmd>lprev<CR>zz")
--
-- -- vim.keymap.set("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
-- -- vim.keymap.set("n", "<leader>x", "<cmd>!chmod +x %<CR>", { silent = true })
--
-- -- vim.keymap.set("n", "<leader>vpp", "<cmd>e ~/.dotfiles/nvim/.config/nvim/lua/theprimeagen/packer.lua<CR>");
-- -- vim.keymap.set("n", "<leader>mr", "<cmd>CellularAutomaton make_it_rain<CR>");
--
-- -- vim.keymap.set("n", "<leader><leader>", function()
-- --     vim.cmd("so")
-- -- end)
